apiVersion: v1
kind: Namespace
metadata:
  name: deletion
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-deletion
  namespace: deletion
spec:
  containers:
  - image: rocketsfang/k8s_concepts
    name: pod-container-1
    imagePullPolicy: IfNotPresent
    comand: []