apiVersion: v1
kind: Namespace
metadata:
  name: pod-livenessprobe
---

apiVersion: v1
kind: Pod
metadata:
  name: pod-livenessprobe
  namespace: pod-livenessprobe
spec:
  containers:
  - image: rocketsfang/k8s_concepts:embeded_db_latest
    name: pod-container-1
    imagePullPolicy: Always
    ports:
    - containerPort: 8888
    livenessProbe:
      exec:
        command: ["ls -l /opt/datastore/probes/livenessprobe.file"]
      initialDelaySeconds: 5
      periodSeconds: 3
      failureThreshold: 2
      timeoutSeconds: 2
  restartPolicy: Never
    