apiVersion: v1
kind: Pod
metadata:
  name: pod-array-demo
spec:
  containers:
  - image: rocketsfang/k8s_concepts
    name: pod-container-1
    imagePullPolicy: Always
    ports:
    - containerPort: 8888
      hostPort: 8888
  - image: rocketsfang/k8s_concepts
    name: pod-container-2
    imagePullPolicy: Always
    command: ["/bin/bash"]
    args: ["-c", "tail -f $(NODEJS_DB_FILE)"]
      
  imagePullSecrets:
  - name: docker-io-account
