apiVersion: v1
kind: Namespace
metadata:
  name: successed
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-successed-demo
  namespace: successed
spec:
  containers:
  - image: rocketsfang/k8s_concepts
    name: pod-container-1
    imagePullPolicy: Always
    command: ["/bin/bash"]
    args: ["-c", "echo 'This is pod lifecycle successed demo.'"]
  restartPolicy: Never