apiVersion: v1
kind: Namespace
metadata:
  name: livenessprobe
---

apiVersion: v1
kind: Pod
metadata:
  name: pod-livenessprobe-demo
  namespace: livenessprobe
spec:
  containers:
  - image: rocketsfang/k8s_concepts
    name: pod-container-1
    imagePullPolicy: Always
    ports:
    - containerPort: 8888
      hostPort: 8888
    livenessProbe:
      httpGet:
        path: /
        port: 8889
      initialDelaySeconds: 15
      timeoutSeconds: 1
    