apiVersion: v1
kind: Namespace
metadata:
  name: pod-deletion
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-deletion
  namespace: pod-deletion
spec:
  containers:
  - image: rocketsfang/k8s_concepts:embeded_db_latest
    name: pod-container
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8888
    lifecycle:
      postStart:
        exec:
          command: "/opt/datastore/container/postStart.sh"
      preStop:
        exec:
          command: "/opt/datastore/container/preStop.sh"