apiVersion: v1
kind: Namespace
metadata:
  name: pod-readinessprobe
---

apiVersion: v1
kind: Pod
metadata:
  name: pod-readinessprobe
  namespace: pod-readinessprobe
spec:
  containers:
  - image: rocketsfang/k8s_concepts:embeded_db_latest
    name: pod-container-1
    imagePullPolicy: Always
    ports:
    - containerPort: 8888
# no port available will cause container schedule failed
#      hostPort: 8888
    livenessProbe:
      httpGet:
        path: /
        port: 8888
      initialDelaySeconds: 15
      timeoutSeconds: 1
    readinessProbe:
      httpGet:
        path: /
        port: 8889
      initialDelaySeconds: 20
      timeoutSeconds: 1
    