apiVersion: v1
kind: Namespace
metadata:
  name: pod-readinessprobe
---

apiVersion: v1
kind: Pod
metadata:
  name: pod-readinessprobe
  namespace: pod-readinessprobe
spec:
  containers:
  - image: rocketsfang/k8s_concepts:db_latest
    name: pod-container-1
    imagePullPolicy: Always
    ports:
    - containerPort: 8888
# no port available will cause container schedule failed
#      hostPort: 8888
# using executing command to probe container
    livenessProbe:
      exec:
        command: ["ls -l /opt/datastore/probes/livenessprobe.file"]
      initialDelaySeconds: 5
      periodSeconds: 3
      failureThreshold: 2
      timeoutSeconds: 2
    readinessProbe:
      exec:
        command: ["ls -l /opt/datastore/probes/readinessprobe.file"]
      initialDelaySeconds: 5
      periodSeconds: 3
      failureThreshold: 2
      timeoutSeconds: 2
  - image: rocketsfang/k8s_concepts:nodejs_latest
    name: pod-container-2
    imagePullPolicy: Always
    ports:
    - containerPort: 8888
# no port available will cause container schedule failed
#      hostPort: 8888
    livenessProbe:
      httpGet:
        path: /
        port: 8888
      initialDelaySeconds: 15
      timeoutSeconds: 1
    readinessProbe:
      httpGet:
        path: /
        port: 8889
      initialDelaySeconds: 20
      timeoutSeconds: 1
