apiVersion: v1
kind: Namespace
metadata:
  name: pod-failed
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-failed
  namespace: pod-failed
spec:
  containers:
  - image: rocketsfang/k8s_concepts:db_latest
    name: pod-container-1
    imagePullPolicy: Always
    command: ["/bin/bash"]
# cat non-existed file
    args: ["-c", "echo 'Oooops, be about failed' && cat /opt/null"]
  restartPolicy: Never