apiVersion: v1
kind: Namespace
metadata:
  name: pod-pending
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-pending
  namespace: pod-pending
spec:
  containers:
# at lest one image is not ready
  - image: rocketsfang/k8s_concepts/non-exist
    name: pod-container-1
    imagePullPolicy: Always
    ports:
    - containerPort: 8888
      hostPort: 8888
  - image: rocketsfang/k8s_concepts:db_latest
    name: pod-container-2
    imagePullPolicy: Always
    ports:
    - containerPort: 8888
      hostPort: 8889    
