apiVersion: v1
kind: Namespace
metadata:
  name: pod-array
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-array-demo
  namespace: pod-array
  labels:
    app: nodejsapp
spec:
  hostAliases:
  - hostnames: [ k8s, concepts, learning ]
    ip: 66.66.66.66
  nodeName: minikube
  hostname: k8s-concepts-learning
  nodeSelector:
    purpose: k8s_concepts_learning
#  Always, OnFailure, Never. Default to Always
  restartPolicy: Never
  shareProcessNamespace: false
  terminationGracePeriodSeconds: 20
  containers:
  - image: rocketsfang/k8s_concepts:nodejs_latest
    name: pod-nodejs
    securityContext:
      privileged: true
    imagePullPolicy: Always
    ports:
    - containerPort: 8888
#      hostPort: 8888
    volumeMounts:
    - name: pod-volume
      mountPath: /opt/datastore/data
  - image: rocketsfang/k8s_concepts:db_latest
    name: pod-db
    imagePullPolicy: Always
    volumeMounts:
    - name: pod-volume
      mountPath: /opt/datastore/data
  volumes:
  - name: pod-volume
    emptyDir:
      medium: Memory
      sizeLimit: 2Mi
# or use the host machine
#  - name: pod-volume
#    type: DirectoryOrCreate
#    path: /home/docker/hostpath/