apiVersion: v1
kind: Namespace
metadata:
  name: pod-running
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-running
  namespace: pod-running
spec:
  restartPolicy: Never
  containers:
  - image: rocketsfang/k8s_concepts:db_latest
    name: pod-container-1
    imagePullPolicy: Always
    ports:
    - containerPort: 8888
      hostPort: 8888
# overwrite the entrypoint to set process can be completed
# while the other container is running
    command: ["/bin/bash"]
    args: ["-c", "echo 'This is pod lifecycle running demo.'"]
  - image: rocketsfang/k8s_concepts:embeded_db_latest
    name: pod-container-2
    imagePullPolicy: Always
    ports:
    - containerPort: 8888
      hostPort: 8889
