apiVersion: v1
kind: Pod
metadata:
  name: pod-running-demo
spec:
  containers:
  - image: rocketsfang/k8s_concepts
    name: pod-container-1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8888
      hostPort: 8888
  - image: rocketsfang/k8s_concepts
    name: pod-container-2
    imagePullPolicy: Never
    ports:
    - containerPort: 8888
      hostPort: 8889
