apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
  - image: rocketsfang/k8s_concepts
    name: pods
    imagePullPolicy: Always
    ports:
    - containerPort: 8888
      hostPort: 8888
  imagePullSecrets:
  - name: docker-io-account
    