apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
  - image: rocketsfang/k8s_concepts
    name: pods
    imagePullPolicy: Always
  imagePullSecrets:
  - name: docker-io-account
    