apiVersion: v1
kind: Namespace
metadata:
  name: pod
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: pod
spec:
  containers:
  - image: rocketsfang/k8s_concepts
    name: pod-container
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8888
# if specified, must match the container ports, mostly it's not set
#   hostPort: 8888