apiVersion: v1
kind: Namespace
metadata:
  name: sts
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodejsapp-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nodejsapp-storage-class
  hostPath:
    path: /home/docker/nodejsapp
    type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: service-nodejsapp
  namespace: sts
  labels:
    app: service-nodejsapp
spec:
  ports:
  - port: 8888
    name: nodejsapp
  clusterIP: None
  selector:
    app: nodejsapp
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-nodejsapp
spec:
  selector:
    matchLabels:
      app: nodejsapp
  serviceName: service-nodejsapp
  replicas: 3
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      terminationGracePeriodSecond: 10
      containers:
      - name: nodejsapp
        image: rocketsfang/k8s_concepts:embeded_db_latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
      volumeMounts:
      - name: nodejsapp-volume-claim
        mountPath: /opt/datastore/data/
  volumeClaimTemplates:
  - metadata:
      name: nodejsapp-volume-claim
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "nodejsapp-storage-class"
      resources:
        requests:
          storage: 1Gi
      
      
      
      
      
