apiVersion: v1
kind: Namespace
metadata:
  name: rs-bare-pods
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nodejsapp
  namespace: rs-bare-pods
  labels:
    app: nodejsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        image: rocketsfang/k8s_concepts:embeded_db_latest
        ports:
        - containerPort: 8888
        
---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: bare-pod-1
#  namespace: rs-bare-pods
# add the labels
#  labels:
#    app: nodejsapp
#spec:
#  containers:
#  - name: nodejsapp
#    image: rocketsfang/k8s_concepts:embeded_db_latest
#    ports:
#    - containerPort: 8888