apiVersion: v1
kind: Namespace
metadata:
  name: rc_label
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nodejsapp
  namespace: rc_label
  labels:
    rc: rc-nodejsapp
spec:
  replicas: 3
  selector:
    app: nodejsapp
    app: nodejsapp_stage
  template:
    metadata:
      name: nodejsapp
      label:
        app: nodejsapp_stage
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        imagePullPolicy: Always
        image: rocketsfang/k8s_concepts:embeded_db_latest
        ports:
        - containerPort: 8888
        
        
        
        