apiVersion: v1
kind: Namespace
metadata:
  name: rs-conflict-label
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nodejsapp
  namespace: rs-conflict-label
  labels:
    app: nodejsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejsapp-stage
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
        app: nodejsapp-stage
        app: nodejsapp-stage-v1
    spec:
      containers:
      - name: nodejsapp
        image: rocketsfang/k8s_concepts:embeded_db_latest
        ports:
        - containerPort: 8888
