apiVersion: v1
kind: Namespace
metadata:
  name: rc_label
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nodejsapp_1
  namespace: rc_label
##  labels:
##    rc: nodejsapp
spec:
  replicas: 3
  selector:
    app: nodejsapp
  template:
    metadata:
      name: nodejsapp
      label:
        app: nodejsapp_1
##  for label created by another RC, what will happens
##      labels:
##       app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        imagePullPolicy: Always
        image: rocketsfang/k8s_concepts:embeded_db_latest
        ports:
        - containerPort: 8888
        
        
        
        