apiVersion: v1
kind: Namespace
metadata:
  name: rc-isolate
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nodejsapp
  namespace: rc-isolate
spec:
  replicas: 2
  selector:
    app: nodejsapp
  template:
    metadata:
      name: nodejsapp
#### kubectl label pod xxxx app=ndejsapp-debug --overwrite
# change the pod label
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        imagePullPolicy: Always
        image: rocketsfang/k8s_concept:embeded_db_latest
        ports:
        - containerPort: 8888