apiVersion: v1
kind: Namespace
metadata:
  name: deploy-rolling-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nodejsapp
  namespace: deploy-rolling-back
  labels:
    app: nodejsapp
spec:
  replicas: 3
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [nodejsapp]}
  strategy:
# for demo rolling update strategy
#    type: Recreate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        image: rocketsfang/k8s_concepts:embeded_db_latest
# for demo rolling back, need a image with wrong name
#        image: rocketsfang/k8s_concepts:embeded_db_latest_rollingupdate_not_existed
        ports:
        - containerPort: 8888
        