apiVersion: v1
kind: Namespace
metadata:
  name: rc-label
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nodejsapp
  namespace: rc-label
  labels:
    rc: rc-nodejsapp
spec:
  replicas: 3
  selector:
# the label order should be exactly match pod label
# 1, the differenct order
# 2, if no label matched, cannot create rc
    app: nodejsapp
    app: nodejsapp-stage
  template:
    metadata:
      name: nodejsapp
      labels:
        app: nodejsapp
        app: nodejsapp-stage
    spec:
      containers:
      - name: nodejsapp
        imagePullPolicy: Always
        image: rocketsfang/k8s_concepts:embeded_db_latest
        ports:
        - containerPort: 8888
        
        
        
        