apiVersion: v1
kind: Namespace
metadata:
  name: rc-service
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nodejsapp
  namespace: rc-service
spec:
  replicas: 3
  selector:
    app: nodejsapp
  tempalte:
    metadata:
      name: nodejsapp
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        imagePullPolicy: Always
        image: rocketsfang/k8s_concepts:embeded_db_latest
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: service-nodejsapp
  namespace: rc-service
spec:
  ports:
  - port: 8888
    protocol: TCP
  selector:
    app: nodejsapp