apiVersion: v1
kind: Namespace
metadata:
  name: rc
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nodejsapp
  namespace: rc
##labels:
##  rc: nodejsapp
spec:
  replicas: 3
  selector:
    app: nodejsapp
  template:
    metadata:
      name: nodejsapp
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        imagePullPolicy: Always
        image: rocketsfang/k8s_concepts:embeded_db_latest
        ports:
        - containerPort: 8888