apiVersion: v1
kind: Namespace
metadata:
  name: deploy-rolling-update
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nodejsapp
  namespace: deploy-rolling-update
  labels:
    app: nodejsapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        image: rocketsfang/k8s_concepts:embeded_db_latest
# for demo rolling update
#        image: rocketsfang/k8s_concepts:embeded_db_latest_rollingupdate
        ports:
        - containerPort: 8888
