apiVersion: v1
kind: Namespace
metadata:
  name: rs
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nodejsapp
  namespace: rs
  labels:
    app: nodejsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejsapp
    matchExpressions:
      - {key: app, operator: In, values: [nodejsapp]}
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        image: rocketsfang/k8s_concepts:embeded_db_latest
        ports:
        - containerPort: 8888